import React from "react";
import { SVGTYPE } from "typings/app";

const DragHandleIcon = (props: SVGTYPE) => {
  const { color = "currentColor", size = "30px" } = props;
  return (
    <svg width="46" height="11" viewBox="0 0 46 11" fill="red">
      <ellipse
        cx="21"
        cy="1.005"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="17"
        cy="1.005"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="13"
        cy="1.005"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="21"
        cy="5.01"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="21"
        cy="9.015"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="17"
        cy="5.01"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="13"
        cy="5.01"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="17"
        cy="9.015"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="13"
        cy="9.015"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="9"
        cy="1.005"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="5"
        cy="1.005"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="1"
        cy="1.005"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="9"
        cy="5.01"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="9"
        cy="9.015"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="5"
        cy="5.01"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="1"
        cy="5.01"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="5"
        cy="9.015"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="1"
        cy="9.015"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="33"
        cy="1.005"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="29"
        cy="1.005"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="25"
        cy="1.005"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="33"
        cy="5.01"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="33"
        cy="9.015"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="29"
        cy="5.01"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="25"
        cy="5.01"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="29"
        cy="9.015"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="25"
        cy="9.015"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="45"
        cy="1.005"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="41"
        cy="1.005"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="37"
        cy="1.005"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="45"
        cy="5.01"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="45"
        cy="9.015"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="41"
        cy="5.01"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="37"
        cy="5.01"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="41"
        cy="9.015"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
      <ellipse
        cx="37"
        cy="9.015"
        rx="1"
        ry="1.001"
        fill={color}
        fill-opacity=".29"
      ></ellipse>
    </svg>
  );
};
export default DragHandleIcon;
