import '@/styles/next-ui.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NextAppProvider from '@/providers/next-ui';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAppProvider>
          <main className="dark text-foreground bg-background">{children}</main>
        </NextAppProvider>
      </body>
    </html>
  );
}
