import '@/styles/globals.scss';
import '@/styles/next-ui.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { twMerge } from 'tailwind-merge';
import NextAppProvider from '@/providers/next-ui';

const inter = Inter({
  subsets: ['latin'],
  weight: 'variable',
  variable: '--inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={inter.style}
        className={twMerge(inter.className, inter.variable)}
      >
        <NextAppProvider>
          <main className="dark text-foreground bg-background">{children}</main>
        </NextAppProvider>
      </body>
    </html>
  );
}
