import React from "react";
import CodeApp from "app";
import Head from "next/head";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CodeApp />
    </React.Fragment>
  );
};

export default Home;
