export enum SEGMENT_FEATURE {
  LAYERS = 'SEGMENT::LAYERS',
  TEMPLATES = 'SEGMENT::TEMPLATES',
}
export enum SEGMENT_SCREEN {
  EDIT = 'SEGMENT::EDIT',
  BACKGROUNDS = 'SEGMENT::BACKGROUNDS',
  ICONS = 'SEGMENT::ICONS',
  ELEMENTS = 'SEGMENT::ELEMENTS',
  FRAMES = 'SEGMENT::FRAMES',
  MORE = 'SEGMENT::MORE',
}

export enum ASIDE_SCREEN {
  EMPTY_SCREEN = '',
  ASPECT_RATIO_SCREEN = 'SCREEN::ASPECT_RATIO_SCREEN',
  PROGRAMMING_LANGUAGE_SCREEN = 'SCREEN::PROGRAMMING_LANGUAGE_SCREEN',
}

export enum BACKGROUND_SCREEN {
  SOLID = 'SCREEN::SOLID',
  GRADIENTS = 'SCREEN::GRADIENTS',
  IMAGES = 'SCREEN::IMAGES',
  MESH = 'SCREEN::MESH',
  PATTERNS = 'SCREEN::PATTERNS',
}
export enum ELEMENTS {
  CODE = 'ELEMENT::CODE',
  TEXT = 'ELEMENT::TEXT',
  IMAGE = 'ELEMENT::IMAGE',
  ICON = 'ELEMENT::ICON',
}

export enum TEXT_ALIGN {
  LEFT = 'left',
  CENTER = 'center',
  RIGHT = 'right',
  JUSTIFY = 'justify',
}

export enum BACKGROUND_TYPE {
  COLOR = 'color',
  GRADIENT = 'gradient',
  IMAGE = 'image',
  VIDEO = 'video',
  PATTERN = 'pattern',
}
